package datagram

import (
	"bytes"
	"encoding/binary"
	"errors"
	"fmt"
	"hash/crc32"
	"math"
	"strings"
	"time"

	"github.com/nil2x/cheburnet/internal/transform"
)

type (
	Ver uint16
	Sum uint32
	Dev int64
	Ses int32
	Num int32
	Cmd int16
)

// Datagram.Len call with empty payload.
const HeaderLen = 2 + 4 + 8 + 4 + 4 + 2

// Datagram.LenEncoded call with empty payload.
var HeaderLenEncoded = New(0, 0, 0, nil).LenEncoded()

// Uniquely represents this device. Changes upon program restart.
var DeviceID = Dev(time.Now().UnixMilli())

var (
	// ErrMalformed indicates that received datagram is corrupted during transmission.
	ErrMalformed = errors.New("datagram is malformed")
)

// Datagram is a packet for data and is used in data exchange between independent
// instances of the program. Main purpose is to implement TCP over UDP network.
type Datagram struct {
	// Structure version. Currently, always 1.
	Version Ver

	// Checksum of entire packet with checksum field equal to 0.
	// Calculated during encoding and verified during decoding.
	Checksum Sum

	// Identifies device that sent a packet.
	// Changes upon program restart.
	Device Dev

	// Identifies connection a packet belongs to.
	// Generated by sender and synced by receiver.
	Session Ses

	// Packet number to implement packet ordering.
	// Have meaning only inside same session.
	// Each device maintains its own number.
	Number Num

	// Specifies packet purpose.
	Command Cmd

	// Specifies command payload.
	Payload []byte
}

// String returns string representation of the datagram.
// Checksum and Device fields are dumped in a short form.
func (dg Datagram) String() string {
	sumShort := dg.Checksum % 1000
	devShort := dg.Device % 1000

	return fmt.Sprintf(
		"ver=%v sum=%v dev=%v ses=%v num=%v cmd=%v pld=%v",
		dg.Version, sumShort, devShort, dg.Session, dg.Number, dg.Command, len(dg.Payload),
	)
}

// Len returns number of bytes the datagram occupies.
func (dg Datagram) Len() int {
	return HeaderLen + len(dg.Payload)
}

// LenEncoded returns number of runes (characters) the datagram will
// occupy after encoding. Note that it doesn't mean neither a number
// of bytes nor a string length, as each rune may occupy more than 1 byte
// depending on charset used during encoding.
func (dg Datagram) LenEncoded() int {
	return 5 * int(math.Ceil(float64(dg.Len())/4))
}

// IsLoopback checks if the datagram is created on the same device
// that is calling this function.
func (dg Datagram) IsLoopback() bool {
	return dg.Device == DeviceID
}

// IsZero checks if the datagram is an empty struct.
func (dg Datagram) IsZero() bool {
	return dg.Version == 0
}

// Clone clones the datagram.
func (dg Datagram) Clone() Datagram {
	dg.Payload = bytes.Clone(dg.Payload)

	return dg
}

// CalcMaxLen calculates maximum Len of datagram based on maximum LenEncoded
// you want to have.
//
// For example, you want number of characters of encoded datagram to be not more
// than maxLenEncoded. To accomplish this, you need datagram whose Len is equal
// or less to value returned by CalcMaxLen.
//
// CalcMaxLen includes header length in calculation. Use CalcMaxLenPayload to get
// only payload length. Knowing maximum payload length, you can use it in New and
// after encoding you will have number of characters that it equal or less to
// maxLenEncoded.
//
// "maximum" because encoding length is varying based on datagram length in bytes.
// maxLenEncoded caps at its maximum, but actual encoded length may be less.
func CalcMaxLen(maxLenEncoded int) int {
	max := 4 * float64(maxLenEncoded) / 5
	min := max - 4
	isValidBase85Len := maxLenEncoded%5 == 0

	if isValidBase85Len {
		return int(max)
	}

	return int(math.Ceil(min))
}

// CalcMaxLenPayload is a CalcMaxLen that excludes header length from calculation.
func CalcMaxLenPayload(maxLenEncoded int) int {
	return CalcMaxLen(maxLenEncoded - HeaderLenEncoded)
}

// New creates a Datagram. The created datagram is intended to be final and
// must not be modified. Next stages are supposed to be encoding and sending.
//
// It is up to you to maintain correct ses and num.
func New(ses Ses, num Num, cmd Cmd, pld []byte) Datagram {
	return Datagram{
		Version:  1,
		Checksum: 0,
		Device:   DeviceID,
		Session:  ses,
		Number:   num,
		Command:  cmd,
		Payload:  pld,
	}
}

// Encode encodes datagram using given charset. Returned value is ready to be sent.
func Encode(dg Datagram, set transform.Base85Charset) string {
	data := make([]byte, 0, dg.Len())

	data = binary.BigEndian.AppendUint16(data, uint16(dg.Version))
	data = binary.BigEndian.AppendUint32(data, uint32(dg.Checksum))
	data = binary.BigEndian.AppendUint64(data, uint64(dg.Device))
	data = binary.BigEndian.AppendUint32(data, uint32(dg.Session))
	data = binary.BigEndian.AppendUint32(data, uint32(dg.Number))
	data = binary.BigEndian.AppendUint16(data, uint16(dg.Command))
	data = append(data, dg.Payload...)

	crc := crc32.ChecksumIEEE(data)
	binary.BigEndian.PutUint32(data[2:6], crc)

	s := transform.ToBase85(data, set)

	return s
}

// Decode decodes encoded datagram and verifies its integrity.
func Decode(s string) (Datagram, error) {
	data, err := transform.FromBase85(s)

	if err != nil {
		return Datagram{}, err
	}

	if len(data) < HeaderLen {
		return Datagram{}, ErrMalformed
	}

	ver := binary.BigEndian.Uint16(data[0:2])
	sum := binary.BigEndian.Uint32(data[2:6])
	dev := binary.BigEndian.Uint64(data[6:14])
	ses := binary.BigEndian.Uint32(data[14:18])
	num := binary.BigEndian.Uint32(data[18:22])
	cmd := binary.BigEndian.Uint16(data[22:24])
	pld := data[HeaderLen:]

	binary.BigEndian.PutUint32(data[2:6], 0)
	crc := crc32.ChecksumIEEE(data)

	if sum != crc {
		return Datagram{}, ErrMalformed
	}

	dg := Datagram{
		Version:  Ver(ver),
		Checksum: Sum(sum),
		Device:   Dev(dev),
		Session:  Ses(ses),
		Number:   Num(num),
		Command:  Cmd(cmd),
		Payload:  pld,
	}

	return dg, nil
}

// Mux combines together encoded datagrams into a single string.
// To revert back, you should Demux first and then Decode each datagram.
//
// If input consist only of one encoded datagram, that datgram is returned
// without modification.
//
// Length of muxed string can be find out using MuxLen.
func Mux(encoded []string) string {
	return strings.Join(encoded, " ")
}

// Demux is a reverse operation of Mux.
func Demux(s string) []string {
	return strings.Split(s, " ")
}

// IsMuxed returns if s is output of Mux and contain two and more datagrams.
func IsMuxed(s string) bool {
	return strings.Contains(s, " ")
}

// MuxLen returns number of runes (characters) that Mux operation will add to
// the final string of n muxed datagrams. To find out length of the final string,
// use MuxLen and LenEncoded together.
func MuxLen(n int) int {
	if n == 0 {
		return 0
	}

	return n - 1
}
