package transform

import (
	"net/url"
	"strings"
)

// ToTextURL transforms normal URL into "text URL".
//
// "text URL" is a string that holds normal URL but the string itself
// is not recognizable as an URL and thus not subject to a bot crawling.
// "text URL" can't be used for request and should be transformed back
// into normal URL before usage for request.
func ToTextURL(s string) string {
	return strings.ReplaceAll(s, ".", ". ")
}

// IsTextURL checks if s is an URL that is created by ToTextURL.
func IsTextURL(s string) bool {
	return strings.HasPrefix(s, "https://")
}

// FromTextURL transforms "text URL" back into normal URL.
func FromTextURL(s string) string {
	return strings.ReplaceAll(s, ". ", ".")
}

// Query is an URL query data that is used by the program.
//
// Query can be used to exchange program data via URL or to identify
// links generated by the program from a non-program links.
//
// In most cases you shouldn't expose program query data to an
// external servers, so use DeleteQuery before making request.
type Query struct {
	Caption string `query:"caption"`
}

// AddQuery embeds query data into the URL as query parameters and returns new URL.
func AddQuery(uri string, query Query) string {
	args := make([]string, 0)

	if len(query.Caption) > 0 {
		args = append(args, "caption="+url.QueryEscape(query.Caption))
	}

	if len(args) == 0 {
		return uri
	}

	arg := strings.Join(args, "&")

	if strings.Contains(uri, "?") {
		uri += "&" + arg
	} else {
		uri += "?" + arg
	}

	return uri
}

// ExtractQuery extracts query data from the URL query parameters.
func ExtractQuery(uri string) (Query, error) {
	parsed, err := url.Parse(uri)

	if err != nil {
		return Query{}, err
	}

	q := parsed.Query()
	query := Query{
		Caption: q.Get("caption"),
	}

	return query, nil
}

// DeleteQuery removes query data from the URL query parameters and returns new URL.
func DeleteQuery(uri string) (string, error) {
	parsed, err := url.Parse(uri)

	if err != nil {
		return "", err
	}

	q := parsed.Query()
	q.Del("caption")

	parsed.RawQuery = q.Encode()
	uri = parsed.String()

	return uri, nil
}
